USE crm;

CREATE TABLE `cacc` (
  `CID` bigint(20) NOT NULL,
  `CGID` bigint(20) DEFAULT NULL,
  `BLANCE` bigint(20) DEFAULT NULL,
  `MARGIN` bigint(20) DEFAULT NULL,
  `FREEMARGIN` bigint(20) DEFAULT NULL,
  `PREBLANCE` bigint(20) DEFAULT NULL,
  `CHANGEBLAN` bigint(20) DEFAULT NULL,
  `PROFITLOSS` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`CID`),
  UNIQUE KEY `CID_UNIQUE` (`CID`),
  UNIQUE KEY `CGID_UNIQUE` (`CGID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8